name: Clang Tidy

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/px4/px4-dev:1.16.0-alpha2
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git ownership workaround
      run: git config --system --add safe.directory '*'

    - name: Install missing deps
      run: apt-get --quiet -y update && DEBIAN_FRONTEND=noninteractive apt-get --quiet -y install clang

    - uses: corrupt952/actions-retry-command@v1.0.7
      with:
        command: make clang-tidy-quiet
        max_attempts: 3
