name: EKF Update Change Indicator

on: push

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/px4/px4-dev:1.16.0-alpha2
    env:
      GIT_COMMITTER_EMAIL: bot@px4.io
      GIT_COMMITTER_NAME: PX4BuildBot
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git ownership workaround
      run: git config --system --add safe.directory '*'

    - name: main test updates change indication files
      run: make tests TESTFILTER=EKF

    - name: Check if there exists diff and save result in variable
      run: echo "CHANGE_INDICATED=$(git diff --exit-code --output=/dev/null || echo $?)" >> $GITHUB_ENV
      working-directory: src/modules/ekf2/test/change_indication

    - name: auto-commit any changes to change indication
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[AUTO COMMIT] update change indication'
        commit_user_name: ${GIT_COMMITTER_NAME}
        commit_user_email: ${GIT_COMMITTER_EMAIL}

    - name: if there is a functional change, fail check
      if: ${{ env.CHANGE_INDICATED }}
      run: exit 1
