name: Nuttx Target with extra env config

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/px4/px4-dev:1.16.0-alpha2
    strategy:
      matrix:
        config: [
          px4_fmu-v5,
          ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git ownership workaround
      run: git config --system --add safe.directory '*'

    - name: make ${{matrix.config}}
      env:
        PX4_EXTRA_NUTTX_CONFIG: "CONFIG_NSH_LOGIN_PASSWORD=\"test\";CONFIG_NSH_CONSOLE_LOGIN=y"
      run: |
        echo "PX4_EXTRA_NUTTX_CONFIG: $PX4_EXTRA_NUTTX_CONFIG"
        make ${{matrix.config}} nuttx_context
        # Check that the config option is set
        grep CONFIG_NSH_LOGIN_PASSWORD build/${{matrix.config}}_default/NuttX/nuttx/.config
